<?php

namespace App\Console\Commands;

use App\Support\PasswordStrength;
use Illuminate\Console\Command;

/**
 * Single source of truth: the password-strength policy lives ONLY in
 * PasswordStrength (PHP). This command serializes it into a dependency-free
 * browser script (window.uvhPasswordPolicy) that the frontend loads before
 * the Angular bundle, so the UI meter and the server-side API gate can never
 * drift apart.
 *
 * Regenerate with:  php artisan uvh:emit-password-policy
 * (Outputs to frontend/public/ and frontend/dist/uvh/browser/ when present.)
 */
class EmitPasswordPolicy extends Command
{
    protected $signature = 'uvh:emit-password-policy {--force : Overwrite existing files}';

    protected $description = 'Emit the shared password-strength policy script for the frontend';

    public function handle(): int
    {
        $js = $this->buildScript();
        // The Compose mount is ./backend-laravel:/app, so the sibling frontend/
        // checkout is not visible inside the container. Write to a stable host
        // path under storage/app instead; the repo tooling copies it into the
        // frontend from there (see scripts/emit-password-policy in composer.json).
        $candidates = [
            storage_path('app/password-policy/uvh-password-policy.v1.js'),
        ];

        $written = [];
        foreach ($candidates as $path) {
            if (! is_dir(dirname($path)) && ! mkdir($concurrentDirectory = dirname($path), 0775, true) && ! is_dir($concurrentDirectory)) {
                continue;
            }
            if (file_exists($path) && ! $this->option('force')
                && md5_file($path) === md5($js)) {
                $this->line('unchanged '.basename(dirname($path)).'/'.basename($path));

                continue;
            }
            file_put_contents($path, $js);
            $written[] = $path;
            $this->info('written '.$path);
        }

        if ($written === []) {
            $this->warn('No output directory found; nothing written.');

            return self::FAILURE;
        }

        return self::SUCCESS;
    }

    private function buildScript(): string
    {
        $policy = [
            'common' => PasswordStrength::COMMON_SUBSTRINGS,
            'patterns' => PasswordStrength::PATTERN_SEQUENCES,
            'rejectWords' => PasswordStrength::REJECT_WORDS,
            'feedback' => PasswordStrength::FEEDBACK,
            'minLength' => PasswordStrength::MIN_LENGTH,
            'maxLength' => PasswordStrength::MAX_LENGTH,
            'acceptMinScore' => PasswordStrength::ACCEPT_MIN_SCORE,
            'bands' => PasswordStrength::BANDS,
        ];

        $json = json_encode(
            $policy,
            JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT,
        );
        if ($json === false) {
            throw new \RuntimeException('Unable to serialize the password policy');
        }

        // Keep the emitted file stable and reviewable: deterministic JSON,
        // no timestamps, and a checksum so drift is detectable at a glance.
        $checksum = hash('sha256', $json);

        return <<<JSEOF
        // Generated by `php artisan uvh:emit-password-policy` — DO NOT EDIT.
        // Source of truth: backend-laravel/app/Support/PasswordStrength.php
        // Policy checksum (sha256 of the JSON payload): {$checksum}
        (function (global) {
          "use strict";
          var policy = {$json};

          function fold(value) {
            return String(value == null ? "" : value)
              .normalize("NFKD")
              .replace(/[\\u0300-\\u036f]/g, "")
              .toLowerCase();
          }

          function containsAny(haystack, needles) {
            for (var i = 0; i < needles.length; i += 1) {
              var needle = needles[i];
              if (needle && haystack.indexOf(needle) !== -1) {
                return true;
              }
            }
            return false;
          }

          function personalCandidates(name, email) {
            var words = fold(name).split(/[^a-z0-9]+/).filter(Boolean);
            var local = fold(String(email == null ? "" : email).split("@")[0]);
            return words.concat([local]);
          }

          // Mirrors PasswordStrength::assess() — see that file for the rules.
          function assess(password, name, email) {
            var value = String(password == null ? "" : password);
            if (value === "") {
              return { score: 0, common: false, personal: false, patterned: false, feedback: policy.feedback.empty };
            }

            var lower = fold(value);
            var common = containsAny(lower, policy.common);
            var patterned = new RegExp("(.)\\\\1{2,}", "u").test(value) || containsAny(lower, policy.patterns);
            var personal = personalCandidates(name, email).some(function (candidate) {
              return candidate.length >= 3 && lower.indexOf(candidate) !== -1;
            });

            var classes = (/[a-z]/.test(value) ? 1 : 0)
              + (/[A-Z]/.test(value) ? 1 : 0)
              + (/\\d/.test(value) ? 1 : 0)
              + (/[^A-Za-z0-9]/.test(value) ? 1 : 0);

            var chars = Array.from(value);
            var unique = new Set(chars).size;
            var ratio = chars.length ? unique / chars.length : 0;

            var score = Math.min(42, chars.length * 3) + classes * 9 + Math.round(ratio * 12);
            if (chars.length >= 14) score += 8;
            if (chars.length >= 18) score += 8;
            if (common) score -= 38;
            if (patterned) score -= 24;
            if (personal) score -= 28;
            if (chars.length < 10) score = Math.min(score, 24);
            score = Math.max(0, Math.min(100, score));

            var feedback = policy.feedback.default;
            if (common) feedback = policy.feedback.common;
            else if (personal) feedback = policy.feedback.personal;
            else if (patterned) feedback = policy.feedback.patterned;
            else if (chars.length < policy.minLength) feedback = policy.feedback.short;
            else if (classes < 3 && chars.length < 16) feedback = policy.feedback.variety;

            return { score: score, common: common, personal: personal, patterned: patterned, feedback: feedback };
          }

          // Mirrors PasswordStrength::isAcceptable() — the server-side gate.
          function isAcceptable(password, name, email) {
            var value = String(password == null ? "" : password);
            var length = Array.from(value).length;
            if (length < policy.minLength || length > policy.maxLength) return false;

            var result = assess(value, name, email);
            if (result.common || result.patterned || result.personal) return false;

            var folded = fold(value);
            for (var i = 0; i < policy.rejectWords.length; i += 1) {
              if (folded.indexOf(policy.rejectWords[i]) !== -1) return false;
            }

            return result.score >= policy.acceptMinScore;
          }

          global.uvhPasswordPolicy = {
            policy: policy,
            assess: assess,
            isAcceptable: isAcceptable,
            strengthLabel: function (score) {
              return score >= policy.bands.strong ? "Fuerte"
                : score >= policy.bands.good ? "Buena"
                : score >= policy.bands.fair ? "Mejorable"
                : "Débil";
            }
          };
        })(typeof window !== "undefined" ? window : globalThis);
        JSEOF;
    }
}
