FROM postgres:18-alpine@sha256:77f585114c32fbca283dc835b0596f4e52b51b4c6662d7810b2f4084f60a1873

COPY docker/postgres/postgresql.conf /etc/uvh-postgres/postgresql.conf
COPY docker/postgres/pg_hba.conf /etc/uvh-postgres/pg_hba.conf
COPY --chmod=755 docker/postgres/10-uvh-roles.sh /docker-entrypoint-initdb.d/10-uvh-roles.sh

USER postgres
CMD ["postgres", "-c", "config_file=/etc/uvh-postgres/postgresql.conf"]
