FROM postgres:16-alpine@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685

COPY docker/postgres/postgresql.conf /etc/uvh-postgres/postgresql.conf
COPY docker/postgres/pg_hba.conf /etc/uvh-postgres/pg_hba.conf
COPY --chmod=755 docker/postgres/10-uvh-roles.sh /docker-entrypoint-initdb.d/10-uvh-roles.sh

USER postgres
CMD ["postgres", "-c", "config_file=/etc/uvh-postgres/postgresql.conf"]
