#!/bin/sh
# Enables TLS on the fixture database so the application can start with
# DB_SSLMODE=verify-full, which is what production requires.
#
# This runs from the image entrypoint during the initdb phase, after PGDATA is
# prepared and before the server that serves traffic is started, so the
# settings are read by the real postmaster on its first start.
#
# This file is bind-mounted, and the entrypoint *sources* a `.sh` hook that is not
# executable and runs it as a child only when it is. Git records it as 644, so on
# a Linux checkout it is sourced. It must therefore be safe to source: it sets no
# shell options (that would leak into the entrypoint and could abort its later
# steps under `nounset`) and never calls `exit`.

cat >> "$PGDATA/postgresql.conf" <<'EOF'

# Release-boot fixture only: throwaway certificate generated by the `certs`
# service. Production terminates database traffic with a real CA chain.
ssl = on
ssl_cert_file = '/tls/server.crt'
ssl_key_file = '/tls/server.key'
EOF
